export const ERROR_CODES = {
  // General
  UNKNOWN: 'UNKNOWN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  TIMEOUT: 'TIMEOUT',
  NOT_FOUND: 'NOT_FOUND',

  // Gateway
  AUTH_FAILED: 'AUTH_FAILED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_CHANNEL: 'INVALID_CHANNEL',
  INVALID_MESSAGE: 'INVALID_MESSAGE',

  // Kernel
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_LIMIT_REACHED: 'SESSION_LIMIT_REACHED',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_BUSY: 'AGENT_BUSY',
  TASK_FAILED: 'TASK_FAILED',
  TASK_TIMEOUT: 'TASK_TIMEOUT',
  QUEUE_FULL: 'QUEUE_FULL',

  // Security
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',

  // AI/LLM
  LLM_API_ERROR: 'LLM_API_ERROR',
  RATE_LIMIT: 'RATE_LIMIT',
  CONTEXT_TOO_LONG: 'CONTEXT_TOO_LONG',
  TOOL_TIMEOUT: 'TOOL_TIMEOUT',
  AGENT_CRASH: 'AGENT_CRASH',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
